// STW Neo offline-first service worker.
// GENERATED by tool/generate_service_worker.dart from tool/sw_template.js —
// edit the template, not build/web/sw.js.
//
// Online: app code is fetched from the network first, so a deploy is live on
// the next load. Offline (or a slow network): served from the cache of the
// last build this browser installed.
'use strict';

const VERSION = '__VERSION__';
const CACHE = 'stw-neo-' + VERSION;

// Needed to start the app offline.
const CORE = __CORE__;

// CanvasKit (Flutter's renderer): Chromium browsers load the optimised
// build, Safari/Firefox the default one. Only the one this browser needs is
// precached.
const CANVASKIT_CHROMIUM = __CANVASKIT_CHROMIUM__;
const CANVASKIT_DEFAULT = __CANVASKIT_DEFAULT__;

// STW PDFs, pdf.js and licences: cached during install too, but a failure
// here does not stop the app from working offline.
const EXTRA = __EXTRA__;

const APP_FILES = new Set([...CORE, ...CANVASKIT_CHROMIUM, ...CANVASKIT_DEFAULT, ...EXTRA]);
const APP_DIRS = ['assets/', 'canvaskit/', 'pdfjs/', 'icons/'];

// Large files that only change with their content: cache first. Every
// build installs a new, empty cache, so a deploy still replaces them.
const CACHE_FIRST_DIRS = ['assets/assets/pdfs/', 'assets/assets/pages/', 'pdfjs/'];

// How long to wait for the network before falling back to the cache.
const NETWORK_TIMEOUT_MS = 4000;

const isChromium = !!(self.navigator && self.navigator.userAgentData);

function fresh(url) {
  return new Request(url, { cache: 'reload' });
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const canvaskit = isChromium ? CANVASKIT_CHROMIUM : CANVASKIT_DEFAULT;
    await cache.addAll([...CORE, ...canvaskit].map(fresh));
    await self.skipWaiting();

    // Heavy extras (PDFs) in the background: not blocking install or launch.
    setTimeout(async () => {
      for (const url of EXTRA) {
        try {
          if (!(await cache.match(url))) await cache.add(fresh(url));
        } catch (e) {
          // Best effort; fetched on demand when opened.
        }
      }
    }, 2000);
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      const ours = key.startsWith('stw-neo-') || key.startsWith('srhu-stw-') ||
        key.startsWith('stwneo-offline-cache');
      if (ours && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

function scopePath(url) {
  const scope = new URL(self.registration.scope);
  return url.pathname.startsWith(scope.pathname)
    ? url.pathname.slice(scope.pathname.length)
    : url.pathname;
}

async function fromCache(request, fallbackUrl) {
  const cache = await caches.open(CACHE);
  return (await cache.match(request, { ignoreSearch: true })) ||
    (fallbackUrl ? await cache.match(fallbackUrl) : undefined);
}

// Network first (latest deploy), cache when offline or after the timeout.
// A response arriving after the timeout still refreshes the cache.
async function networkFirst(request, fallbackUrl) {
  const network = fetch(request).then(async (response) => {
    if (response && response.ok && response.type === 'basic') {
      const cache = await caches.open(CACHE);
      await cache.put(request, response.clone());
    }
    return response;
  });
  const timeout = new Promise((resolve) => setTimeout(resolve, NETWORK_TIMEOUT_MS));
  try {
    const response = await Promise.race([network, timeout]);
    if (response && response.ok) return response;
  } catch (e) {
    // Offline: fall through to the cache.
  }
  const cached = await fromCache(request, fallbackUrl);
  if (cached) return cached;
  try {
    return await network;
  } catch (e) {
    return Response.error();
  }
}

async function cacheFirst(request) {
  const cached = await fromCache(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok && response.type === 'basic') {
      const cache = await caches.open(CACHE);
      await cache.put(request, response.clone());
    }
    return response;
  } catch (e) {
    return Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request, 'index.html'));
    return;
  }

  const path = scopePath(url);
  // Only the app's own files; anything else (e.g. an API on the same host)
  // goes straight to the network.
  if (!APP_FILES.has(path) && !APP_DIRS.some((d) => path.startsWith(d))) return;

  if (CACHE_FIRST_DIRS.some((d) => path.startsWith(d))) {
    event.respondWith(cacheFirst(request));
  } else {
    event.respondWith(networkFirst(request));
  }
});
