// SRHU STW offline service worker.
// GENERATED by tool/generate_service_worker.dart from tool/sw_template.js —
// edit the template, not build/web/sw.js.
'use strict';

const VERSION = '__VERSION__';
const CACHE = 'srhu-stw-' + VERSION;

// Needed to start the app offline.
const CORE = __CORE__;

// CanvasKit (Flutter's renderer): Chromium browsers load the optimised
// build, Safari/Firefox the default one. Only the one this browser needs is
// precached.
const CANVASKIT_CHROMIUM = __CANVASKIT_CHROMIUM__;
const CANVASKIT_DEFAULT = __CANVASKIT_DEFAULT__;

// STW PDFs, pdf.js and licences: cached during install too, but a failure
// here does not stop the app from working offline.
const EXTRA = __EXTRA__;

// Fetched from the network first so new releases arrive promptly; the cache
// is the offline fallback.
const NETWORK_FIRST = ['', 'index.html', 'flutter_bootstrap.js', 'manifest.json', 'version.json'];

const isChromium = !!(self.navigator && self.navigator.userAgentData);

function fresh(url) {
  return new Request(url, { cache: 'reload' });
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const canvaskit = isChromium ? CANVASKIT_CHROMIUM : CANVASKIT_DEFAULT;
    await cache.addAll([...CORE, ...canvaskit].map(fresh));
    await Promise.all(EXTRA.map(async (url) => {
      try {
        await cache.add(fresh(url));
      } catch (e) {
        // Best effort; fetched again when first opened.
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('srhu-stw-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

function scopePath(url) {
  const scope = new URL(self.registration.scope);
  return url.pathname.startsWith(scope.pathname)
    ? url.pathname.slice(scope.pathname.length)
    : url.pathname;
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await fetch(request);
    if (response.ok) cache.put(request, response.clone());
    return response;
  } catch (e) {
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;
    if (request.mode === 'navigate') {
      const shell = await cache.match('index.html');
      if (shell) return shell;
    }
    return Response.error();
  }
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, { ignoreSearch: true });
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok && response.type === 'basic') cache.put(request, response.clone());
  return response;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const path = scopePath(url);
  if (request.mode === 'navigate' || NETWORK_FIRST.includes(path)) {
    event.respondWith(networkFirst(request));
  } else {
    event.respondWith(cacheFirst(request));
  }
});
