// STW Neo offline-first service worker.
// GENERATED by tool/generate_service_worker.dart from tool/sw_template.js —
// edit the template, not build/web/sw.js.
'use strict';

const VERSION = '__VERSION__';
const CACHE = 'stw-neo-' + VERSION;

// Needed to start the app offline.
const CORE = __CORE__;

// CanvasKit (Flutter's renderer): Chromium browsers load the optimised
// build, Safari/Firefox the default one. Only the one this browser needs is
// precached.
const CANVASKIT_CHROMIUM = __CANVASKIT_CHROMIUM__;
const CANVASKIT_DEFAULT = __CANVASKIT_DEFAULT__;

// STW PDFs, pdf.js and licences: cached during install too, but a failure
// here does not stop the app from working offline.
const EXTRA = __EXTRA__;

// Core shell assets that use Stale-While-Revalidate: served instantly from cache,
// revalidated in background when online.
const SHELL_ASSETS = ['', 'index.html', 'flutter_bootstrap.js', 'manifest.json', 'version.json'];

const isChromium = !!(self.navigator && self.navigator.userAgentData);

function fresh(url) {
  return new Request(url, { cache: 'reload' });
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const canvaskit = isChromium ? CANVASKIT_CHROMIUM : CANVASKIT_DEFAULT;
    // Core runtime shell assets (fast & necessary for offline boot)
    await cache.addAll([...CORE, ...canvaskit].map(fresh));
    await self.skipWaiting();

    // Background prefetch for heavy extras (PDFs): does not block install or steal launch bandwidth
    setTimeout(async () => {
      for (const url of EXTRA) {
        try {
          const match = await cache.match(url);
          if (!match) await cache.add(fresh(url));
        } catch (e) {
          // Best effort; fetched on demand when opened.
        }
      }
    }, 2000);
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if ((key.startsWith('stw-neo-') || key.startsWith('srhu-stw-')) && key !== CACHE) {
        await caches.delete(key);
      }
    }
    await self.clients.claim();
  })());
});

function scopePath(url) {
  const scope = new URL(self.registration.scope);
  return url.pathname.startsWith(scope.pathname)
    ? url.pathname.slice(scope.pathname.length)
    : url.pathname;
}

// Stale-While-Revalidate for app entry & shell:
// Returns the local cached copy immediately (0ms wait) so the app opens
// instantly like a native app. Revalidates from network in the background if connected.
async function staleWhileRevalidate(request, fallbackUrl) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, { ignoreSearch: true }) ||
                 (fallbackUrl ? await cache.match(fallbackUrl) : null);

  const fetchPromise = fetch(request).then(async (response) => {
    if (response && response.ok) {
      await cache.put(request, response.clone());
    }
    return response;
  }).catch(() => null);

  if (cached) {
    return cached;
  }

  const networkResponse = await fetchPromise;
  if (networkResponse && networkResponse.ok) return networkResponse;

  if (fallbackUrl) {
    const fallback = await cache.match(fallbackUrl);
    if (fallback) return fallback;
  }

  return Response.error();
}

// Cache-First for static assets (JS, WASM, CSS, images, fonts, PDFs):
// Serves instantly from local cache; never re-requests already cached files.
async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, { ignoreSearch: true });
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok && (response.type === 'basic' || response.type === 'cors')) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (e) {
    return Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const path = scopePath(url);

  // Navigation requests (launching the PWA or tapping direct routes):
  if (request.mode === 'navigate') {
    event.respondWith(staleWhileRevalidate(request, 'index.html'));
    return;
  }

  // Core shell files: Stale-While-Revalidate for instant startup + background update
  if (SHELL_ASSETS.includes(path)) {
    event.respondWith(staleWhileRevalidate(request, null));
    return;
  }

  // All other static assets (WASM, JS chunks, fonts, images, PDFs, CSS): Cache-First
  event.respondWith(cacheFirst(request));
});
