/// Hinglish (romanised Hindi) → English used to understand chatbot questions.
///
/// Only for understanding the question: answers are always verbatim STW
/// text. Phrases are replaced before single words. An empty value drops the
/// word (grammatical particles).
library;

/// Multi-word phrases, applied first (longest first).
const hinglishPhrases = <String, String>{
  'kya nahi karna': 'what not do',
  'kya nahi karni': 'what not do',
  'kya nahi karein': 'what not do',
  'kya galti nahi': 'what mistake avoid',
  'galti nahi': 'mistake avoid',
  'kab nahi': 'when not',
  'nahi dena': 'not give',
  'nahi dein': 'not give',
  'na dein': 'not give',
  'mat dein': 'not give',
  'ya nahi': 'or no',
  'kya karein': 'what to do',
  'kya kare': 'what to do',
  'kya karna hai': 'what to do',
  'kya karna': 'what to do',
  'kya dein': 'what to give',
  'kya dete': 'what give',
  'kitni baar': 'how often',
  'kitni der': 'how often',
  'kab tak': 'how long until',
  'kam karein': 'reduce',
  'kam kare': 'reduce',
  'kam karna': 'reduce',
  'band karein': 'stop',
  'band kar': 'stop',
  'band karna': 'stop',
  'kaise pata': 'how know',
  'kaise samjhein': 'how know',
  'feed ke baad': 'after feeding',
  'ke baad': 'after',
  'se pehle': 'before',
  'kis hafte': 'which weeks',
  'full form': 'full form',
  'sugar low': 'low blood glucose',
  'sugar kam': 'low blood glucose',
  'low hai': 'low',
  'theek ho raha': 'improving',
  'sudhar nahi': 'not improving',
  'pad rahe': 'having',
  'de sakte': 'can give',
  'dena chahiye': 'should give',
  'se bade': 'above',
  'se badi': 'above',
  'se zyada': 'above',
  'se kam': 'below',
  'kaisa dikhta': 'look like signs',
  'kaisa lagta': 'look like signs',
};

/// Single words.
const hinglishWords = <String, String>{
  // Question words
  'kab': 'when',
  'kitna': 'how much',
  'kitni': 'how much',
  'kitne': 'how many',
  'kyun': 'why',
  'kyon': 'why',
  'kaise': 'how',
  'kese': 'how',
  'kya': 'what',
  'kaun': 'which',
  'kaunsa': 'which',
  'kaunsi': 'which',
  'konsa': 'which',
  'konsi': 'which',
  'kin': 'which',
  'kis': 'which',
  'kisko': 'whom',
  'kise': 'whom',
  // Negation
  'nahi': 'not',
  'nahin': 'not',
  'nai': 'not',
  'mat': 'not',
  // Verbs
  'dena': 'give',
  'dein': 'give',
  'dete': 'give',
  'diya': 'given',
  'lagayein': 'start',
  'lagana': 'start',
  'shuru': 'start',
  'chalu': 'start',
  'rokna': 'stop',
  'rokein': 'stop',
  'badhayein': 'increase',
  'badhana': 'increase',
  'badha': 'increase',
  'badhaye': 'increase',
  'bhejna': 'refer',
  'bhejein': 'refer',
  'karein': 'do',
  'karna': 'do',
  'kare': 'do',
  'karni': 'do',
  'karo': 'do',
  'kar': 'do',
  'sakte': 'can',
  'sakta': 'can',
  'chahiye': 'should',
  // People
  'bacha': 'newborn',
  'baccha': 'newborn',
  'bacche': 'newborn',
  'bachcha': 'newborn',
  'bachche': 'newborn',
  'baccho': 'newborn',
  'bacchon': 'newborn',
  'bachon': 'newborn',
  'shishu': 'newborn',
  'navjat': 'newborn',
  'navjaat': 'newborn',
  'garbhvati': 'pregnant',
  'mahila': 'woman',
  'maa': 'mother',
  // Clinical words
  'sugar': 'blood glucose',
  'shakkar': 'blood glucose',
  'jaanch': 'examination screening',
  'janch': 'examination screening',
  'aankh': 'eye',
  'aankhon': 'eye',
  'ankh': 'eye',
  'saans': 'breathing respiratory',
  'sans': 'breathing respiratory',
  'takleef': 'distress',
  'taklif': 'distress',
  'pareshani': 'distress',
  'lakshan': 'symptoms signs',
  'pehchane': 'recognise signs',
  'pehchanein': 'recognise signs',
  'pehchan': 'recognise signs',
  'bimari': 'disease',
  'ilaj': 'treatment',
  'upchar': 'treatment',
  'dawa': 'drug',
  'dawai': 'drug',
  'khuraak': 'dose',
  'pehli': 'first',
  'pehla': 'first',
  'pehle': 'before',
  'baad': 'after',
  'ghante': 'hours',
  'ghanta': 'hour',
  'din': 'days',
  'hafte': 'weeks',
  'hafta': 'weeks',
  'saptah': 'weeks',
  'theek': 'normal',
  'thik': 'normal',
  'sudhar': 'improving',
  'bigad': 'worsening',
  'taiyari': 'prepare',
  'intezaam': 'arrange',
  'vyavastha': 'arrange',
  'bachav': 'prevent',
  'bachayein': 'prevent',
  'galti': 'mistake avoid',
  'zaroori': 'needed',
  'fayda': 'benefit',
  'fayde': 'benefit',
  'faida': 'benefit',
  'pichla': 'previous',
  'dobara': 'repeat',
  'turant': 'immediately',
  'jaldi': 'quickly',
  'lambe': 'long',
  'samay': 'time',
  'halki': 'mild',
  'halka': 'mild',
  'gambhir': 'severe',
  'kam': 'low',
  'zyada': 'more',
  'jyada': 'more',
  'daure': 'seizures',
  'piliya': 'jaundice',
  'mausam': 'weather',
  // Particles (dropped)
  'hai': '',
  'hain': '',
  'ho': '',
  'tha': '',
  'thi': '',
  'me': '',
  'mein': '',
  'ka': '',
  'ki': '',
  'ke': '',
  'ko': '',
  'se': '',
  'par': '',
  'pe': '',
  'aur': 'and',
  'ya': 'or',
  'agar': 'if',
  'tak': 'until',
  'wale': '',
  'wala': '',
  'wali': '',
  'raha': '',
  'rahi': '',
  'rahe': '',
  'chal': '',
  'bilkul': '',
  'aaya': '',
  'aaye': '',
  'gaya': '',
};
