#!/usr/bin/env python3
"""
tools/add_ancs_hypo_regions.py

Adds (or replaces) the curated regions of the ANCS and Neonatal Hypoglycemia
STW posters in assets/regions/regions.json. Boxes are the PDF's own card
rectangles (vector drawings, in PDF points), padded by 2 pt and normalised to
the page size. Run tools/build_region_text.py afterwards to fill "text" and
render the crops:

    python tools/add_ancs_hypo_regions.py
    python tools/build_region_text.py \
        Antenatal_Corticosteroids_for_Preterm_Birth_8th_Oct.pdf \
        Neonatal_Hypoglycemia_8th_Oct.pdf
"""

import json
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGIONS_JSON_PATH = os.path.join(PROJECT_ROOT, "assets", "regions", "regions.json")

ANCS_DOC = "Antenatal_Corticosteroids_for_Preterm_Birth_8th_Oct.pdf"
HYPO_DOC = "Neonatal_Hypoglycemia_8th_Oct.pdf"
PAGE_W, PAGE_H = 841.89, 1633.68  # both posters
PAD = 2.0


def region(rid, doc, title, rtype, section, box, aliases, questions):
    x0, y0, x1, y1 = box
    x0, y0 = max(0.0, x0 - PAD), max(0.0, y0 - PAD)
    x1, y1 = min(PAGE_W, x1 + PAD), min(PAGE_H, y1 + PAD)
    return {
        "id": rid,
        "document": doc,
        "page": 1,
        "title": title,
        "type": rtype,
        "section": section,
        "x": round(x0 / PAGE_W, 5),
        "y": round(y0 / PAGE_H, 5),
        "w": round((x1 - x0) / PAGE_W, 5),
        "h": round((y1 - y0) / PAGE_H, 5),
        "aliases": aliases,
        "example_questions": questions,
    }


ANCS = [
    region("ancs_introduction", ANCS_DOC,
           "Introduction: Antenatal Corticosteroids (ACS)", "text", "Introduction",
           (7, 221, 503, 328),
           ["antenatal corticosteroids", "acs", "antenatal steroids",
            "benefits of acs", "why give acs", "steroid ke fayde"],
           ["What are the benefits of antenatal corticosteroids?",
            "Why are antenatal steroids used before preterm birth?",
            "ACS dene se kya fayda hota hai?",
            "Antenatal steroid kyun dete hain?"]),
    region("ancs_when_to_give", ANCS_DOC,
           "When to Give ACS", "text", "When to give",
           (513, 221, 835, 328),
           ["when to give acs", "24+0 to 33+6 weeks", "gestation window",
            "acs timing", "acs kab dena hai", "kitne hafte"],
           ["When should antenatal corticosteroids be given?",
            "At what gestational age is ACS given?",
            "ACS kab dena chahiye?",
            "Kitne hafte ki pregnancy me steroid dete hain?"]),
    region("ancs_eligibility", ANCS_DOC,
           "ACS Eligibility Criteria", "text", "Eligibility criteria",
           (7, 341, 504, 629),
           ["eligibility criteria", "acs eligibility", "spontaneous preterm labour",
            "pprom", "antepartum hemorrhage", "severe pre-eclampsia", "eclampsia",
            "planned preterm birth", "early usg", "acs ke criteria", "eligible"],
           ["What are the eligibility criteria for ACS?",
            "Which pregnant women are eligible for antenatal corticosteroids?",
            "Is ACS given in PPROM?",
            "ACS kis mahila ko dena chahiye?",
            "PPROM me steroid de sakte hain?",
            "Preterm labour me ACS ke criteria kya hain?"]),
    region("ancs_drug_dose", ANCS_DOC,
           "Drug & Dose: Dexamethasone for ACS", "text", "Drug & dose",
           (513, 342, 835, 509),
           ["dexamethasone", "dexamethasone sodium phosphate", "6 mg im",
            "every 12 hours", "4 doses", "betamethasone", "acs dose", "dexa dose",
            "steroid dose", "dexamethasone kitna dena hai", "acs ka dose"],
           ["What is the dose of dexamethasone for ACS?",
            "ACS ka dose kya hai?",
            "Dexamethasone kitna dena hai?",
            "Why is dexamethasone preferred over betamethasone?",
            "Betamethasone kyun nahi dete?",
            "Steroid ki khuraak kitni hai?"]),
    region("ancs_when_not_to_give", ANCS_DOC,
           "When NOT to Give ACS", "text", "When not to give",
           (513, 513, 835, 628),
           ["contraindications", "when not to give", "acs contraindication",
            "chorioamnionitis", "systemic maternal infection", "34 weeks",
            "≥34 weeks", "routine use", "acs kab nahi dena",
            "steroids not given", "should not be given"],
           ["When should ACS not be given?",
            "When should antenatal steroids not be given?",
            "Contraindications of antenatal corticosteroids",
            "Is ACS given at 34 weeks or more?",
            "ACS kab nahi dena chahiye?",
            "Chorioamnionitis me steroid de sakte hain?"]),
    region("ancs_special_situations", ANCS_DOC,
           "Special Situations: Multiple Pregnancy, FGR, Hypertension, Diabetes",
           "text", "Special situations",
           (7, 642, 360, 792),
           ["special situations", "multiple pregnancy", "twins",
            "fetal growth restriction", "fgr", "hypertensive disorders",
            "diabetes in pregnancy", "maternal glucose control", "twins me steroid"],
           ["Can ACS be given in twins or multiple pregnancy?",
            "Is ACS given in diabetes in pregnancy?",
            "ACS in fetal growth restriction",
            "Diabetic mother ko steroid dena chahiye?",
            "Twins pregnancy me ACS de sakte hain?"]),
    region("ancs_repeat_course", ANCS_DOC,
           "When to Give a Repeat ACS Course", "text", "Repeat course",
           (371, 642, 835, 792),
           ["repeat course", "repeat acs", "second course", "7 days earlier",
            "one repeat course", "fetal harm", "dobara steroid", "repeat dose"],
           ["When can a repeat course of ACS be given?",
            "How many repeat courses of ACS are allowed?",
            "Repeat steroid course kab dete hain?",
            "Kya dobara ACS de sakte hain?",
            "Second course of antenatal steroids after 7 days"]),
    region("ancs_documentation", ANCS_DOC,
           "ACS Documentation", "text", "Documentation",
           (7, 804, 361, 949),
           ["documentation", "document", "record", "case sheet", "mcp card",
            "referral slip", "next dose due", "kahan likhein"],
           ["What should be documented when giving ACS?",
            "Where to record ACS doses?",
            "ACS ki documentation kaise karein?",
            "MCP card me kya likhna hai?"]),
    region("ancs_referral", ANCS_DOC,
           "Referral / In-utero Transfer for ACS", "text", "Referral/transfer",
           (371, 804, 835, 949),
           ["referral", "transfer", "in-utero transfer", "level ii care",
            "level i facility", "first dose before referral", "refer pregnant woman"],
           ["When should a pregnant woman be referred for in-utero transfer?",
            "Can a level I facility give the first dose of ACS?",
            "In-utero transfer kab karna chahiye?",
            "Referral se pehle pehla dose de sakte hain?"]),
    region("ancs_dos", ANCS_DOC,
           "ACS Clinical DOs", "text", "DOs",
           (0, 957, 410, 1112),
           ["dos", "clinical dos", "acs dos", "kya karna chahiye"],
           ["What are the DOs for antenatal corticosteroids?",
            "ACS dete samay kya karna chahiye?"]),
    region("ancs_donts", ANCS_DOC,
           "ACS Clinical DON'Ts", "text", "DON'Ts",
           (419, 957, 842, 1112),
           ["donts", "acs donts", "kya nahi karna"],
           ["What should be avoided with antenatal corticosteroids?",
            "ACS ke DON'Ts kya hain?",
            "Do not delay birth or referral to complete the ACS course"]),
    region("ancs_kpis", ANCS_DOC,
           "ACS Key Performance Indicators", "table", "KPIs",
           (0, 1116, 842, 1224),
           ["kpi", "kpis", "key performance indicators", "acs coverage",
            "appropriate acs use", "80%", "95%"],
           ["What are the KPIs for antenatal corticosteroids?",
            "ACS coverage target kya hai?",
            "How is ACS coverage calculated?"]),
    region("ancs_abbreviations", ANCS_DOC,
           "ACS Abbreviations", "text", "Abbreviations",
           (0, 1450, 842, 1527),
           ["abbreviations", "full form", "pprom full form", "mcp card full form"],
           ["What is the full form of PPROM?",
            "MCP ka full form kya hai?"]),
]

HYPO = [
    region("hypo_whom_to_screen", HYPO_DOC,
           "Whom to Screen for Hypoglycemia", "text", "Whom to screen",
           (8, 241, 826, 417),
           ["whom to screen", "at-risk neonates", "risk factors", "low birth weight",
            "lbw", "sga", "lga", "intergrowth-21st", "infant of diabetic mother",
            "idm", "beta-blockers", "exchange transfusion", "sick neonates",
            "healthy term aga", "sugar check kisko"],
           ["Which neonates should be screened for hypoglycemia?",
            "Who is at risk of neonatal hypoglycemia?",
            "Kis bacche ka sugar check karna chahiye?",
            "Diabetic mother ke bacche ka sugar check karein?",
            "Is glucose monitoring needed in healthy term AGA babies?"]),
    region("hypo_monitoring_schedule", HYPO_DOC,
           "Schedule of Blood Glucose Monitoring", "table", "Monitoring schedule",
           (16, 427, 295, 588),
           ["schedule", "monitoring schedule", "1, 2, 6, 12, 24, 48, 72 hours",
            "how often", "iv fluids every 6-8 hours", "pre-feeding",
            "24-36 hours", "kitne ghante"],
           ["How often should blood glucose be monitored in at-risk infants?",
            "Blood glucose monitoring schedule for neonates",
            "Sugar kitne ghante par check karna hai?",
            "When can BG monitoring be stopped in IDM?"]),
    region("hypo_how_to_monitor", HYPO_DOC,
           "How to Monitor Blood Glucose (BG)", "text", "How to monitor",
           (537, 428, 826, 580),
           ["glucometer", "point-of-care", "lab sample", "lab confirmation",
            "do not delay treatment", "how to measure", "sugar kaise check"],
           ["How should blood glucose be measured in neonates?",
            "Should treatment wait for lab confirmation of low glucose?",
            "Glucometer se sugar kaise check karein?",
            "Lab report ka wait karein ya treatment shuru karein?"]),
    region("hypo_flowchart_entry", HYPO_DOC,
           "Blood Glucose <45 mg/dL", "algorithm", "Flowchart entry",
           (328, 475, 502, 503),
           ["45 mg/dl", "<45 mg/dl", "hypoglycemia cutoff", "low blood glucose",
            "sugar kam"],
           ["What is the blood glucose cutoff for neonatal hypoglycemia?",
            "Kitne sugar ko low maante hain newborn me?",
            "Hypoglycemia definition in neonates"]),
    region("hypo_symptoms", HYPO_DOC,
           "Symptoms and Signs of Hypoglycemia", "text", "Symptoms and signs",
           (214, 594, 627, 686),
           ["symptoms", "signs", "lethargy", "jitteriness", "tremors",
            "convulsions", "cyanosis", "apnoea", "high-pitched cry", "unable to feed",
            "lakshan"],
           ["What are the symptoms of neonatal hypoglycemia?",
            "Signs of low blood sugar in newborn",
            "Bacche me sugar kam hone ke lakshan kya hain?",
            "Jitteriness and lethargy in hypoglycemia"]),
    region("hypo_asymptomatic_branch", HYPO_DOC,
           "Asymptomatic & BG ≥25 mg/dL: Supervised Feeding", "algorithm",
           "Asymptomatic branch",
           (11, 688, 416, 759),
           ["asymptomatic", "no symptoms", "symptoms nahi", "bina symptoms",
            "bg ≥25", "supervised feeding", "breastfeeding", "expressed breastmilk",
            "ebm", "formula", "paladai", "gavage", "feed karayein"],
           ["Management of asymptomatic hypoglycemia with BG 25 or more",
            "BG 30 aur symptoms nahi, kya karein?",
            "Asymptomatic baby with low sugar - should we feed?",
            "Paladai or gavage feeding in hypoglycemia"]),
    region("hypo_recheck_1h", HYPO_DOC,
           "Re-check BG After 1 Hour", "algorithm", "Re-check after 1 hour",
           (13, 777, 416, 883),
           ["re-check after 1 hour", "1 hour", "recheck", "continue feeds",
            "6 hourly for 24 hours", "symptoms develop", "ek ghante baad"],
           ["When to recheck blood glucose after feeding?",
            "What if BG is still below 45 after 1 hour of feeding?",
            "Feed ke 1 ghante baad sugar check karna hai?",
            "When to start IV glucose infusion after feeding?"]),
    region("hypo_symptomatic_branch", HYPO_DOC,
           "Symptomatic or BG <25 mg/dL: IV Bolus and Dextrose Infusion",
           "algorithm", "Symptomatic branch",
           (458, 688, 825, 758),
           ["symptomatic", "bg <25", "<25 mg/dl", "iv bolus", "2 ml/kg",
            "10% dextrose", "d10", "gir 6", "6 mg/kg/min", "bolus dose",
            "dextrose kitna"],
           ["Management of symptomatic neonatal hypoglycemia",
            "What is the dextrose bolus dose for hypoglycemia?",
            "BG below 25 mg/dL treatment",
            "Dextrose bolus kitna dena hai?",
            "Symptomatic baby ko kitna GIR shuru karein?"]),
    region("hypo_recheck_30min", HYPO_DOC,
           "Re-check BG Every 30 Minutes on IV Glucose", "algorithm",
           "Re-check every 30 min",
           (458, 779, 825, 812),
           ["every 30 min", "30 minutes", "2 consecutive values", "every 6 h",
            "recheck on iv"],
           ["How often to recheck BG after starting IV dextrose?",
            "IV glucose ke baad sugar kitni der me check karein?"]),
    region("hypo_increase_gir", HYPO_DOC,
           "BG <45 mg/dL on IV: Increase GIR (maximum 12 mg/kg/min)", "algorithm",
           "Increase GIR",
           (459, 833, 642, 946),
           ["increase gir", "gir by 2", "maximum 12 mg/kg/min", "max gir",
            "gir badhana", "gir badhayein"],
           ["How much to increase GIR if BG stays low?",
            "What is the maximum GIR?",
            "GIR kitna badhayein?",
            "Sugar low rehne par GIR kaise badhayein?"]),
    region("hypo_persistent_refractory", HYPO_DOC,
           "Persistent or Refractory Hypoglycemia: Consider Endocrine/Metabolic "
           "Disorders & Refer", "algorithm", "Persistent / refractory",
           (454, 969, 647, 1146),
           ["persistent hypoglycemia", "refractory hypoglycemia", "gir >10-12",
            "3-7 days", "endocrine", "metabolic", "refer to higher centre"],
           ["What is refractory hypoglycemia?",
            "When to refer a baby with persistent hypoglycemia?",
            "Refractory hypoglycemia me refer kab karein?",
            "Persistent hypoglycemia definition GIR requirement"]),
    region("hypo_euglycemic_wean", HYPO_DOC,
           "BG ≥45 mg/dL on IV: Euglycemic for 24 Hours, Reduce GIR", "algorithm",
           "Wean GIR",
           (665, 833, 832, 1050),
           ["euglycemic", "24 hours", "reduce gir", "wean gir", "every 6 hours",
            "increase oral feeds", "gir kam karna"],
           ["How to wean IV dextrose in hypoglycemia?",
            "How to reduce GIR once sugar is normal?",
            "GIR kaise kam karein?",
            "When to start reducing glucose infusion?"]),
    region("hypo_stop_iv", HYPO_DOC,
           "Stop IV Fluids (Euglycemic on GIR 4 mg/kg/min)", "algorithm",
           "Stop IV fluids",
           (665, 1072, 832, 1146),
           ["stop iv fluids", "gir 4", "4 mg/kg/min", "tolerating enteral feeds",
            "iv band karna"],
           ["When to stop IV fluids in neonatal hypoglycemia?",
            "IV fluids kab band karein?",
            "Stop IV glucose at what GIR?"]),
    region("hypo_drugs_refractory", HYPO_DOC,
           "Drugs for Refractory Hypoglycemia", "text", "Drugs",
           (458, 1167, 838, 1239),
           ["hydrocortisone", "5 mg/kg/day", "two divided doses", "drugs",
            "tertiary care", "refractory dawa"],
           ["Which drugs are used for refractory hypoglycemia?",
            "Hydrocortisone dose for hypoglycemia",
            "Refractory hypoglycemia me kya dete hain?",
            "Hydrocortisone kitna dena hai?"]),
    region("hypo_prevention", HYPO_DOC,
           "Prevention of Hypoglycemia", "text", "Prevention",
           (13, 888, 416, 962),
           ["prevention", "prevent", "early breastfeeding", "normothermia",
            "do not feed dextrose", "bachav"],
           ["How to prevent neonatal hypoglycemia?",
            "Hypoglycemia se kaise bachayein?",
            "Can dextrose be fed instead of breastmilk?"]),
    region("hypo_practical_points", HYPO_DOC,
           "Practical Points for IV Glucose", "text", "Practical points",
           (15, 966, 416, 1108),
           ["practical points", "peripheral vein", "12.5-15% dextrose",
            "iv cannula", "syringe pump", "infusion pump", "frequent boluses",
            "underlying cause", "polycythemia", "meningitis", "iugr"],
           ["Maximum dextrose concentration through a peripheral vein",
            "Practical points for glucose infusion",
            "Peripheral line me kitna dextrose de sakte hain?",
            "Search for underlying cause of hypoglycemia"]),
    region("hypo_dos", HYPO_DOC,
           "Hypoglycemia Clinical DOs", "text", "DO's",
           (0, 1247, 381, 1322),
           ["dos", "clinical dos", "hypoglycemia dos", "monitor bg in all"],
           ["What are the DOs in neonatal hypoglycemia?",
            "Hypoglycemia me kya karna chahiye?"]),
    region("hypo_donts", HYPO_DOC,
           "Hypoglycemia Clinical DON'Ts", "text", "DON'Ts",
           (396, 1247, 842, 1322),
           ["donts", "antibiotics", "mother-infant dyad", "substitute dextrose"],
           ["What should not be done in neonatal hypoglycemia?",
            "Should antibiotics be given for hypoglycemia?",
            "Hypoglycemia me kya nahi karna chahiye?"]),
    region("hypo_kpis", HYPO_DOC,
           "Hypoglycemia Key Performance Indicators", "table", "KPIs",
           (0, 1323, 842, 1418),
           ["kpi", "kpis", "key performance indicators", "screening coverage",
            "timely bg re-check", "90%"],
           ["What are the KPIs for neonatal hypoglycemia?",
            "Blood glucose screening coverage target"]),
    region("hypo_neuro_followup", HYPO_DOC,
           "Neurodevelopmental Follow-up after Hypoglycemia", "text", "Follow-up",
           (0, 1419, 842, 1457),
           ["neurodevelopmental follow-up", "structured follow-up",
            "recurrent hypoglycemia", "severe hypoglycemia"],
           ["Which babies with hypoglycemia need neurodevelopmental follow-up?",
            "Hypoglycemia ke baad follow-up kab chahiye?"]),
]


def main():
    with open(REGIONS_JSON_PATH, "r", encoding="utf-8") as f:
        regions = json.load(f)
    keep = [r for r in regions if r["document"] not in (ANCS_DOC, HYPO_DOC)]
    merged = keep + ANCS + HYPO
    with open(REGIONS_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(merged, f, indent=2, ensure_ascii=False)
    print(f"{len(keep)} existing + {len(ANCS)} ANCS + {len(HYPO)} hypoglycemia "
          f"regions -> {REGIONS_JSON_PATH}")


if __name__ == "__main__":
    main()
