{{flutter_js}}
{{flutter_build_config}}

// Remove the HTML loading screen once Flutter has drawn its first frame.
window.addEventListener('flutter-first-frame', function () {
  var splash = document.getElementById('splash');
  if (splash) {
    splash.style.opacity = '0';
    setTimeout(function () { splash.remove(); }, 260);
  }
});

// Flutter's own service worker is deprecated (it only unregisters itself),
// so it is not requested here; offline support comes from sw.js below.
_flutter.loader.load();

// Offline support: sw.js is generated by tool/generate_service_worker.dart
// for release builds (tool/build_web.sh). Debug builds have no sw.js and
// registration simply fails.
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('sw.js').catch(function (e) {
      console.info('Offline support unavailable:', e && e.message);
    });
  });
}
